# Generated by Django 3.1 on 2021-07-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'variacion', 'verbose_name_plural': 'variaciones'},
        ),
    ]
