# Generated by Django 3.1 on 2021-07-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_reviewrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Reseña/Rating', 'verbose_name_plural': 'Reseñas/Ratings'},
        ),
    ]
