# Generated by Django 3.1 on 2021-07-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Galería Producto', 'verbose_name_plural': 'Galerías Productos'},
        ),
    ]
